apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../../lakehouse-otel-backend-secret.yaml
patches:
  - path: otel-backend-config-patch.yaml
  - target:
      kind: Deployment
      name: otel-collector
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: turbalance-otel-backend
