apiVersion: v1
kind: Secret
metadata:
  name: turbalance-api-auth
  namespace: turbalance-lakehouse
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: turbalance-collector-auth
  namespace: turbalance-lakehouse
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: turbalance-discovery-auth
  namespace: turbalance-lakehouse
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: turbalance-agent-client-ca
  namespace: turbalance-lakehouse
$patch: delete
