apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: turbalance-ingestion
  labels:
    app.kubernetes.io/name: turbalance-ingestion
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: turbalance-ingestion
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      bearerTokenSecret:
        name: turbalance-ingestion-secrets
        key: metrics-token
