apiVersion: 1
datasources:
  - name: turbalance API
    uid: turbalance-api
    type: marcusolsson-json-datasource
    access: proxy
    url: http://api-server:8080
    isDefault: false
    editable: true
    jsonData:
      timeout: 10
